import type { NextPage } from 'next'
import Head from 'next/head'
import { Grid } from "@material-ui/core"
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios"
import { useRouter } from "next/router"
import React, { useEffect, useState } from "react"
import { Button, Form } from "semantic-ui-react"


const Home: NextPage = () => {
  const router = useRouter()
  const [username, setUsermane] = useState("")
  const [password, setPassword] = useState("")



  const loginHandle = () => {
    axios
      .get(`/api/login?username=${username}&password=${password}`)
      .then((res) => {
        console.log(res)
        router.push("/posts")
      })
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
      className="formContainer"
      container
      justifyContent="center"
      alignItems="center"
    >
      <Form>
        <Form.Field>
          <input
            onChange={(event) => setUsermane(event.target.value)}
            placeholder="Username"
          />
        </Form.Field>
        <Form.Field>
          <input
            onChange={(event) => setPassword(event.target.value)}
            placeholder="Password"
          />
        </Form.Field>
        <Button primary onClick={() => loginHandle()} type="submit">
          Submit
        </Button>
      </Form>
    </Grid>
    
      <footer className={styles.footer}>
      
        <p>ibiytest</p>
        <p> ibiy2021</p>
      </footer>
    </div>
  )
}


export default Home
